---
- hosts: windows
  gather_facts: false

  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Install IIS
      win_feature:
        name: web-server
        include_management_tools: true
        include_sub_features: true
        state: present

    - name: Copy index.html to wwwroot
      win_copy:
        src: index.html
        dest: C:\inetpub\wwwroot\index.html
        force: true

    - name: Create logs directory
      win_file:
        path: c:\logs
        state: directory

    - name: install dotnet core iis hosting module with no frameworks
      win_chocolatey:
        name: "dotnetcore-windowshosting"
        version: "3.1.0"
        # yamllint disable-line rule:line-length
        install_args: "OPT_NO_RUNTIME=1 OPT_NO_SHAREDFX=1 OPT_NO_X86=1 OPT_NO_SHARED_CONFIG_CHECK=1"
        state: present
      notify: restart IIS

  handlers:
    - name: restart IIS
      win_shell: '& {iisreset}'
