name: Ansible Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Lint Ansible Playbooks
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          .github/actions/ansible/action.yml
          .github/actions/ansible/configure_iis_web_server.yml
          .github/actions/ansible/configure_nginx_web_server.yml
          .github/actions/ansible/hosts_azure_rm.yml
          .github/actions/ansible/roles/requirements.yml
          .github/actions/ansible/site.yml
          .github/workflows/deploy_ansible.yml